### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [devjin0617/ripplectron#8]
Hi, I want to design a new logo for the project completely free...

**Comment by devjin0617** [comment]
oh! thank you! 😄 no problem.

**Comment by Arslanshn** [comment]
https://drive.google.com/drive/folders/1fhmu9Qz-vH1Mhc7Fr5pcp_zECG5dXEbY?usp=sharing

**Comment by Arslanshn** [comment]
Hello I hope you like the logo:)

**Comment by Arslanshn** [comment]
When do you think about using the logo I made? :-)

**Comment by devjin0617** [comment]
progress in April : )

**Comment by Arslanshn** [comment]
Will you let me know when you use the arrow
:-)

**Comment by Arslanshn** [comment]
Hi dejvin will you use the logo...

**Comment by Arslanshn** [comment]
Hello 😀

**Comment by Arslanshn** [comment]
Hi😀

**Comment by Arslanshn** [comment]
Hello dejvin..
